name: Generate Contribution Art

on:
  # Runs every minute (minimum GitHub Actions interval)
  schedule:
    - cron: "* * * * *"
  # Allows manual trigger
  workflow_dispatch:

jobs:
  build:
    name: Make Contribution Art
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: jasineri/gitartwork@v1
        with:
          # Use your username
          user_name: raimonvibe
          # Your custom text (could be your name, a message, etc)
          text: RAIMONVIBE
          # Configure text appearance
          text_color: "#36BCF7"
          background: "#0D1117"
          # Adjust layout
          line_height: 100
          
      - uses: jasineri/simple-push-action@v1
