name: Generate Contribution Art

on:
  # Runs every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  # Allows manual trigger
  workflow_dispatch:

jobs:
  build:
    name: Make Contribution Art
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: jasineri/gitartwork@v1
        with:
          # Use your username
          user_name: raimonvibe
          # Your custom text (could be your name, a message, etc)
          text: raimonvibe
          
      - uses: jasineri/simple-push-action@v1
