name: Generate Contribution Art

on:
  # Runs every minute (minimum GitHub Actions interval)
  schedule:
    - cron: "* * * * *"
  # Allows manual trigger
  workflow_dispatch:

jobs:
  build:
    name: Make Contribution Art
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Generate Contribution Art
        uses: jasineri/gitartwork@v1
        with:
          # Use your username
          user_name: raimonvibe
          # Your custom text (could be your name, a message, etc)
          text: < / CODER >
          # Configure text appearance
          text_color: "#36BCF7,#FF5733,#FFC300,#DAF7A6,#C70039" # Multicolor gradient for text
          background: "linear-gradient(to bottom, #000000, #333333)" # Black to dark gray gradient background
          # Adjust layout
          line_height: 100
          
      - name: Push Changes
        uses: jasineri/simple-push-action@v1
