name: Generate Contribution Art

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Make Contribution Art
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Contribution Art
        uses: jasineri/gitartwork@v1
        with:
          user_name: raimon
          text: CODE

      - name: Push Changes
        uses: jasineri/simple-push-action@v1
